version: '3'
services:
  postgresql:
    image: postgres:latest
    container_name: ProjectHubDB
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=scott
      - POSTGRES_PASSWORD=tiger
